import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mitchell
 */
public class ProjectFrame extends javax.swing.JFrame {
    int Tabletype;
    GameModel games;
    List<Info> glist;
    /**
     * Creates new form ProjectFrame
     */
    public ProjectFrame(GameModel model) {
        initComponents();
        games = model;
        setLocationRelativeTo(null);
        Table.setLocationRelativeTo(null);
        AllSystemTable.setLocationRelativeTo(null);
        Info.setLocationRelativeTo(null);
        AdvancedSearch.setLocationRelativeTo(null);
        AdvancedSearch1.setLocationRelativeTo(null);
        jSplitPane1.setEnabled(false);
        InfoButton.setEnabled(false);
        InfoButton1.setEnabled(false);
    }

    public void settable(int Tabletype){
        DefaultTableModel dtm = (DefaultTableModel) GameTable.getModel();
        for(int i = 0;i < dtm.getRowCount();i++){
            dtm.removeRow(i);
            i--;
        }
        try {
            games.makeGames(Tabletype);
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(ProjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        glist = games.getGames();
        for(Info game:glist){
            Object[] entry = {game.getTitle(),game.getESRB(),game.getGenre(),game.getRating()};
            dtm.addRow(entry);
        }
        InfoButton.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table = new javax.swing.JDialog();
        AdvancedSearchButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        Searchbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        GameTable = new javax.swing.JTable();
        InfoButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        WiiUMenuItem = new javax.swing.JMenuItem();
        WiiMenuItem = new javax.swing.JMenuItem();
        GamecubeMenuItem = new javax.swing.JMenuItem();
        N64MenuItem = new javax.swing.JMenuItem();
        Nintendo3DSMenuItem = new javax.swing.JMenuItem();
        NintendoDSMenuItem = new javax.swing.JMenuItem();
        GBAMenuItem = new javax.swing.JMenuItem();
        GBCMenuItem = new javax.swing.JMenuItem();
        PS4MenuItem = new javax.swing.JMenuItem();
        PS3MenuItem = new javax.swing.JMenuItem();
        PS2MenuItem = new javax.swing.JMenuItem();
        PSVMenuItem = new javax.swing.JMenuItem();
        PSPMenuItem = new javax.swing.JMenuItem();
        XboxOneMenuItem = new javax.swing.JMenuItem();
        Xbox360MenuItem = new javax.swing.JMenuItem();
        XboxMenuItem = new javax.swing.JMenuItem();
        MacMenuItem = new javax.swing.JMenuItem();
        PCMenuItem = new javax.swing.JMenuItem();
        LinuxMenuItem = new javax.swing.JMenuItem();
        MainPageMenuItem = new javax.swing.JMenuItem();
        AdvancedSearch = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        AdSearch = new javax.swing.JButton();
        Title = new javax.swing.JTextField();
        ESRB = new javax.swing.JTextField();
        Genre = new javax.swing.JTextField();
        Rating = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        CancelAS = new javax.swing.JButton();
        Info = new javax.swing.JDialog();
        JScrollPane = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        Summarypane = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Picturepane = new javax.swing.JTextPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        Exit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        AllSystemTable = new javax.swing.JDialog();
        AdvancedSearchButton1 = new javax.swing.JButton();
        ResetButton1 = new javax.swing.JButton();
        SearchButton1 = new javax.swing.JButton();
        Searchbox1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        GameTable1 = new javax.swing.JTable();
        InfoButton1 = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MainPageMenuItem1 = new javax.swing.JMenuItem();
        AdvancedSearch1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        AdSearch1 = new javax.swing.JButton();
        Title1 = new javax.swing.JTextField();
        ESRB1 = new javax.swing.JTextField();
        Genre1 = new javax.swing.JTextField();
        Rating1 = new javax.swing.JTextField();
        Sys1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        CancelAS1 = new javax.swing.JButton();
        WiiButton = new javax.swing.JButton();
        WiiUButton = new javax.swing.JButton();
        Nintendo64Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NintendoDSButton = new javax.swing.JButton();
        Nintendo3DSButton = new javax.swing.JButton();
        GBCButton = new javax.swing.JButton();
        GBAButton = new javax.swing.JButton();
        GamecubeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PS4Button = new javax.swing.JButton();
        PSVButton = new javax.swing.JButton();
        PS3Button = new javax.swing.JButton();
        PSPButton = new javax.swing.JButton();
        PS2Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        XboxOneButton = new javax.swing.JButton();
        Xbox360Button = new javax.swing.JButton();
        XboxButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        MacButton = new javax.swing.JButton();
        PCButton = new javax.swing.JButton();
        LinuxButton = new javax.swing.JButton();
        AllButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        Table.setMinimumSize(new java.awt.Dimension(725, 434));
        Table.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                TableWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                TableWindowClosed(evt);
            }
        });

        AdvancedSearchButton.setText("Advanced Search");
        AdvancedSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancedSearchButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset Table");
        ResetButton.setPreferredSize(new java.awt.Dimension(29, 29));
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        Searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchboxActionPerformed(evt);
            }
        });

        GameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "ESRB", "Genre", "Rating"
            }
        ));
        GameTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GameTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GameTable);

        InfoButton.setText("More Info");
        InfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Change Table");

        WiiUMenuItem.setText("Wii U");
        WiiUMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiiUMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(WiiUMenuItem);

        WiiMenuItem.setText("Wii");
        WiiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiiMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(WiiMenuItem);

        GamecubeMenuItem.setText("Gamecube");
        GamecubeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamecubeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(GamecubeMenuItem);

        N64MenuItem.setText("Nintendo 64");
        N64MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N64MenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(N64MenuItem);

        Nintendo3DSMenuItem.setText("Nintendo 3DS");
        Nintendo3DSMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nintendo3DSMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(Nintendo3DSMenuItem);

        NintendoDSMenuItem.setText("Nintendo DS");
        NintendoDSMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NintendoDSMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(NintendoDSMenuItem);

        GBAMenuItem.setText("Gameboy Advance");
        GBAMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBAMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(GBAMenuItem);

        GBCMenuItem.setText("Gameboy Color");
        GBCMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBCMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(GBCMenuItem);

        PS4MenuItem.setText("Playstation 4");
        PS4MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS4MenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PS4MenuItem);

        PS3MenuItem.setText("Playstation 3");
        PS3MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS3MenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PS3MenuItem);

        PS2MenuItem.setText("Playstation 2");
        PS2MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS2MenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PS2MenuItem);

        PSVMenuItem.setText("Playstation Vita");
        PSVMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSVMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PSVMenuItem);

        PSPMenuItem.setText("Playstation Portable");
        PSPMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSPMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PSPMenuItem);

        XboxOneMenuItem.setText("Xbox One");
        XboxOneMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XboxOneMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(XboxOneMenuItem);

        Xbox360MenuItem.setText("Xbox 360");
        Xbox360MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xbox360MenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(Xbox360MenuItem);

        XboxMenuItem.setText("Xbox");
        XboxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XboxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(XboxMenuItem);

        MacMenuItem.setText("Mac");
        MacMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(MacMenuItem);

        PCMenuItem.setText("PC");
        PCMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PCMenuItem);

        LinuxMenuItem.setText("Linux");
        LinuxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinuxMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(LinuxMenuItem);

        MainPageMenuItem.setText("Main Page");
        MainPageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPageMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(MainPageMenuItem);

        jMenuBar1.add(jMenu1);

        Table.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout TableLayout = new javax.swing.GroupLayout(Table.getContentPane());
        Table.getContentPane().setLayout(TableLayout);
        TableLayout.setHorizontalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(TableLayout.createSequentialGroup()
                .addComponent(Searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdvancedSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TableLayout.setVerticalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableLayout.createSequentialGroup()
                .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(AdvancedSearchButton)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );

        AdvancedSearch.setMinimumSize(new java.awt.Dimension(525, 280));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Advanced Search"));

        AdSearch.setText("Search");
        AdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdSearchActionPerformed(evt);
            }
        });

        Title.setToolTipText("");

        jLabel27.setText("Game Title");

        jLabel28.setText("ESRB Rating");

        jLabel29.setText("Game Genre");

        jLabel30.setText("Game Rating");

        CancelAS.setText("Cancel");
        CancelAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rating, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Genre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ESRB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelAS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdSearch)
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ESRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelAS)
                    .addComponent(AdSearch))
                .addContainerGap())
        );

        javax.swing.GroupLayout AdvancedSearchLayout = new javax.swing.GroupLayout(AdvancedSearch.getContentPane());
        AdvancedSearch.getContentPane().setLayout(AdvancedSearchLayout);
        AdvancedSearchLayout.setHorizontalGroup(
            AdvancedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        AdvancedSearchLayout.setVerticalGroup(
            AdvancedSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdvancedSearchLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Info.setMinimumSize(new java.awt.Dimension(670, 490));
        Info.setUndecorated(true);

        jSplitPane1.setDividerLocation(335);

        Summarypane.setEditable(false);
        Summarypane.setColumns(20);
        Summarypane.setLineWrap(true);
        Summarypane.setRows(5);
        jScrollPane5.setViewportView(Summarypane);

        jSplitPane1.setRightComponent(jScrollPane5);

        jScrollPane4.setViewportView(Picturepane);

        jSplitPane1.setLeftComponent(jScrollPane4);

        JScrollPane.setViewportView(jSplitPane1);

        Exit.setText("Exit");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Exit.add(jMenuItem1);

        jMenuBar2.add(Exit);

        Info.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout InfoLayout = new javax.swing.GroupLayout(Info.getContentPane());
        Info.getContentPane().setLayout(InfoLayout);
        InfoLayout.setHorizontalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        InfoLayout.setVerticalGroup(
            InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        AllSystemTable.setMinimumSize(new java.awt.Dimension(725, 434));
        AllSystemTable.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                AllSystemTableWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                AllSystemTableWindowClosed(evt);
            }
        });

        AdvancedSearchButton1.setText("Advanced Search");
        AdvancedSearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancedSearchButton1ActionPerformed(evt);
            }
        });

        ResetButton1.setText("Reset Table");
        ResetButton1.setPreferredSize(new java.awt.Dimension(29, 29));
        ResetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButton1ActionPerformed(evt);
            }
        });

        SearchButton1.setText("Search");
        SearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton1ActionPerformed(evt);
            }
        });

        Searchbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchbox1ActionPerformed(evt);
            }
        });

        GameTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "ESRB", "Genre", "System", "Rating"
            }
        ));
        GameTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GameTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GameTable1);

        InfoButton1.setText("More Info");
        InfoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButton1ActionPerformed(evt);
            }
        });

        jMenu2.setText("Main Menu");

        MainPageMenuItem1.setText("Main Page");
        MainPageMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPageMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(MainPageMenuItem1);

        jMenuBar3.add(jMenu2);

        AllSystemTable.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout AllSystemTableLayout = new javax.swing.GroupLayout(AllSystemTable.getContentPane());
        AllSystemTable.getContentPane().setLayout(AllSystemTableLayout);
        AllSystemTableLayout.setHorizontalGroup(
            AllSystemTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(AllSystemTableLayout.createSequentialGroup()
                .addComponent(Searchbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdvancedSearchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ResetButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AllSystemTableLayout.setVerticalGroup(
            AllSystemTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllSystemTableLayout.createSequentialGroup()
                .addGroup(AllSystemTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton1)
                    .addComponent(AdvancedSearchButton1)
                    .addComponent(ResetButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );

        AdvancedSearch1.setMinimumSize(new java.awt.Dimension(550, 370));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Advanced Search"));

        AdSearch1.setText("Search");
        AdSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdSearch1ActionPerformed(evt);
            }
        });

        Title1.setToolTipText("");

        jLabel32.setText("Game Title");

        jLabel33.setText("ESRB Rating");

        jLabel34.setText("Game Genre");

        jLabel35.setText("Game Rating");

        jLabel36.setText("System");

        CancelAS1.setText("Cancel");
        CancelAS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAS1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelAS1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdSearch1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel35))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(23, 23, 23))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rating1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Genre1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ESRB1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sys1)
                            .addComponent(Title1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ESRB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rating1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sys1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelAS1)
                    .addComponent(AdSearch1)))
        );

        javax.swing.GroupLayout AdvancedSearch1Layout = new javax.swing.GroupLayout(AdvancedSearch1.getContentPane());
        AdvancedSearch1.getContentPane().setLayout(AdvancedSearch1Layout);
        AdvancedSearch1Layout.setHorizontalGroup(
            AdvancedSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedSearch1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdvancedSearch1Layout.setVerticalGroup(
            AdvancedSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvancedSearch1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Game Database");

        WiiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wii.jpg"))); // NOI18N
        WiiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiiButtonActionPerformed(evt);
            }
        });

        WiiUButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wii-u-fancy-shot.jpeg"))); // NOI18N
        WiiUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiiUButtonActionPerformed(evt);
            }
        });

        Nintendo64Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/N64.jpg"))); // NOI18N
        Nintendo64Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nintendo64ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Nintendo Consoles:");

        NintendoDSButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NintendoDS.jpeg"))); // NOI18N
        NintendoDSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NintendoDSButtonActionPerformed(evt);
            }
        });

        Nintendo3DSButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ninendo3DS.jpeg"))); // NOI18N
        Nintendo3DSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nintendo3DSButtonActionPerformed(evt);
            }
        });

        GBCButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gameboy color.jpg"))); // NOI18N
        GBCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBCButtonActionPerformed(evt);
            }
        });

        GBAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GBA.jpg"))); // NOI18N
        GBAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBAButtonActionPerformed(evt);
            }
        });

        GamecubeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gamecube.jpg"))); // NOI18N
        GamecubeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamecubeButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Sony Consoles:");

        PS4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PS4.jpg"))); // NOI18N
        PS4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS4ButtonActionPerformed(evt);
            }
        });

        PSVButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PSvita.jpg"))); // NOI18N
        PSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSVButtonActionPerformed(evt);
            }
        });

        PS3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PS3.jpg"))); // NOI18N
        PS3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS3ButtonActionPerformed(evt);
            }
        });

        PSPButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PSP.jpg"))); // NOI18N
        PSPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSPButtonActionPerformed(evt);
            }
        });

        PS2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PS2.jpg"))); // NOI18N
        PS2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PS2ButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Microsoft Consoles:");

        XboxOneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xboxone.jpg"))); // NOI18N
        XboxOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XboxOneButtonActionPerformed(evt);
            }
        });

        Xbox360Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xbox360.jpg"))); // NOI18N
        Xbox360Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Xbox360ButtonActionPerformed(evt);
            }
        });

        XboxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xbox.jpg"))); // NOI18N
        XboxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XboxButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Computer Systems:");

        MacButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mac.jpg"))); // NOI18N
        MacButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacButtonActionPerformed(evt);
            }
        });

        PCButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Microsoft.jpg"))); // NOI18N
        PCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCButtonActionPerformed(evt);
            }
        });

        LinuxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Linux.jpg"))); // NOI18N
        LinuxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinuxButtonActionPerformed(evt);
            }
        });

        AllButton.setText("All Systems");
        AllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel5.setText("VGDB");

        jLabel6.setText("Wii U");

        jLabel7.setText("Wii");

        jLabel8.setText("Gamecube");

        jLabel9.setText("Nintendo 64");

        jLabel10.setText("Nintendo 3DS");

        jLabel11.setText("Nintendo DS");

        jLabel12.setText("Gameboy Advance");

        jLabel13.setText("Gameboy Color");

        jLabel14.setText("Playstation 4");

        jLabel15.setText("Playstation 3");

        jLabel16.setText("Playstation 2");

        jLabel17.setText("Playstation Vita");

        jLabel18.setText("Playstation Portable");

        jLabel19.setText("Xbox One");

        jLabel20.setText("Xbox 360");

        jLabel21.setText("Xbox");

        jLabel22.setText("Mac");

        jLabel23.setText("PC");

        jLabel24.setText("Linux");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Zelda.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel17)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PSVButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PSPButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(XboxOneButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Xbox360Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(XboxButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(jLabel20)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel21))
                                            .addComponent(jLabel19)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MacButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PCButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LinuxButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel22)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel23)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel24)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(WiiUButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WiiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GamecubeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nintendo64Button))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PS4Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PS3Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PS2Button))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel10)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel11)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(104, 104, 104)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Nintendo3DSButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NintendoDSButton)
                                                .addGap(0, 0, 0)
                                                .addComponent(GBAButton)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel13))
                                            .addComponent(GBCButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(303, 303, 303)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel14)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel15))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6)
                                .addGap(388, 388, 388)
                                .addComponent(jLabel9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllButton)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nintendo64Button)
                    .addComponent(WiiUButton)
                    .addComponent(WiiButton)
                    .addComponent(GamecubeButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GBCButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GBAButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NintendoDSButton)
                                .addComponent(Nintendo3DSButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PS3Button)
                    .addComponent(PS4Button)
                    .addComponent(PS2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PSVButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)))
                            .addComponent(PSPButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(XboxOneButton)
                                    .addComponent(Xbox360Button)
                                    .addComponent(XboxButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addComponent(jLabel21))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MacButton)
                            .addComponent(PCButton)
                            .addComponent(LinuxButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel25)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllButtonActionPerformed
        AllSystemTable.setVisible(true);
        Tabletype = 11;
        DefaultTableModel dtm = (DefaultTableModel) GameTable1.getModel();
        for(int i = 0;i < dtm.getRowCount();i++){
            dtm.removeRow(i);
            i--;
        }
        try {
            games.makeGames(Tabletype);
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(ProjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        glist = games.getGames();
        for(Info game:glist){
            Object[] entry = {game.getTitle(),game.getESRB(),game.getGenre(),game.getSystem(),game.getRating()};
            dtm.addRow(entry);
        }
        setVisible(false);
    }//GEN-LAST:event_AllButtonActionPerformed

    private void WiiUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiiUButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 3;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_WiiUButtonActionPerformed

    private void XboxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XboxButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 7;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_XboxButtonActionPerformed

    private void SearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchboxActionPerformed

    }//GEN-LAST:event_SearchboxActionPerformed

    private void Nintendo3DSMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nintendo3DSMenuItemActionPerformed
        Tabletype = 12;
        settable(Tabletype);
    }//GEN-LAST:event_Nintendo3DSMenuItemActionPerformed

    private void NintendoDSMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NintendoDSMenuItemActionPerformed
        Tabletype = 13;
        settable(Tabletype);
    }//GEN-LAST:event_NintendoDSMenuItemActionPerformed

    private void GBAMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBAMenuItemActionPerformed
        Tabletype = 14;
        settable(Tabletype);
    }//GEN-LAST:event_GBAMenuItemActionPerformed

    private void PS4MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS4MenuItemActionPerformed
        Tabletype = 6;
        settable(Tabletype);
    }//GEN-LAST:event_PS4MenuItemActionPerformed

    private void Xbox360MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xbox360MenuItemActionPerformed
        Tabletype = 8;
        settable(Tabletype);
    }//GEN-LAST:event_Xbox360MenuItemActionPerformed

    private void WiiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiiButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 2;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_WiiButtonActionPerformed

    private void GamecubeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamecubeButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 1;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_GamecubeButtonActionPerformed

    private void Nintendo64ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nintendo64ButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 0;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_Nintendo64ButtonActionPerformed

    private void Nintendo3DSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nintendo3DSButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 12;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_Nintendo3DSButtonActionPerformed

    private void NintendoDSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NintendoDSButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 13;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_NintendoDSButtonActionPerformed

    private void GBAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBAButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 14;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_GBAButtonActionPerformed

    private void GBCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBCButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 15;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_GBCButtonActionPerformed

    private void PS4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS4ButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 6;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_PS4ButtonActionPerformed

    private void PS3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS3ButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 5;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_PS3ButtonActionPerformed

    private void PS2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS2ButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 16;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_PS2ButtonActionPerformed

    private void PSVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSVButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 17;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_PSVButtonActionPerformed

    private void PSPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSPButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 18;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_PSPButtonActionPerformed

    private void XboxOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XboxOneButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 9;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_XboxOneButtonActionPerformed

    private void PCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 4;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_PCButtonActionPerformed

    private void Xbox360ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Xbox360ButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 8;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_Xbox360ButtonActionPerformed

    private void MacButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 10;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_MacButtonActionPerformed

    private void LinuxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinuxButtonActionPerformed
        Table.setVisible(true);
        Tabletype = 19;
        settable(Tabletype);
        setVisible(false);
    }//GEN-LAST:event_LinuxButtonActionPerformed

    private void WiiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiiMenuItemActionPerformed
        Tabletype = 2;
        settable(Tabletype);
    }//GEN-LAST:event_WiiMenuItemActionPerformed

    private void WiiUMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiiUMenuItemActionPerformed
        Tabletype = 3;
        settable(Tabletype);
    }//GEN-LAST:event_WiiUMenuItemActionPerformed

    private void GamecubeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamecubeMenuItemActionPerformed
        Tabletype = 1;
        settable(Tabletype);
    }//GEN-LAST:event_GamecubeMenuItemActionPerformed

    private void N64MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N64MenuItemActionPerformed
        Tabletype = 0;
        settable(Tabletype);
    }//GEN-LAST:event_N64MenuItemActionPerformed

    private void GBCMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBCMenuItemActionPerformed
        Tabletype = 15;
        settable(Tabletype);
    }//GEN-LAST:event_GBCMenuItemActionPerformed

    private void PS3MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS3MenuItemActionPerformed
        Tabletype = 5;
        settable(Tabletype);
    }//GEN-LAST:event_PS3MenuItemActionPerformed

    private void PSVMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSVMenuItemActionPerformed
        Tabletype = 17;
        settable(Tabletype);
    }//GEN-LAST:event_PSVMenuItemActionPerformed

    private void PS2MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PS2MenuItemActionPerformed
        Tabletype = 16;
        settable(Tabletype);
    }//GEN-LAST:event_PS2MenuItemActionPerformed

    private void XboxOneMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XboxOneMenuItemActionPerformed
        Tabletype = 9;
        settable(Tabletype);
    }//GEN-LAST:event_XboxOneMenuItemActionPerformed

    private void XboxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XboxMenuItemActionPerformed
        Tabletype = 7;
        settable(Tabletype);
    }//GEN-LAST:event_XboxMenuItemActionPerformed

    private void MacMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacMenuItemActionPerformed
        Tabletype = 10;
        settable(Tabletype);
    }//GEN-LAST:event_MacMenuItemActionPerformed

    private void PCMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCMenuItemActionPerformed
        Tabletype = 4;
        settable(Tabletype);
    }//GEN-LAST:event_PCMenuItemActionPerformed

    private void LinuxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinuxMenuItemActionPerformed
        Tabletype = 19;
        settable(Tabletype);
    }//GEN-LAST:event_LinuxMenuItemActionPerformed

    private void MainPageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPageMenuItemActionPerformed
        Table.dispose();
        InfoButton.setEnabled(false);
        setVisible(true);
    }//GEN-LAST:event_MainPageMenuItemActionPerformed

    private void TableWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TableWindowClosed
        setVisible(true);
        InfoButton.setEnabled(false);
    }//GEN-LAST:event_TableWindowClosed

    private void TableWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TableWindowClosing
        setVisible(true);
        InfoButton.setEnabled(false);
    }//GEN-LAST:event_TableWindowClosing

    private void PSPMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSPMenuItemActionPerformed
        Tabletype = 18;
        settable(Tabletype);
    }//GEN-LAST:event_PSPMenuItemActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        ResetButtonActionPerformed(evt);
        if(Searchbox.getText().equals("") != true){
            int x,y,keep = 0;
            String value;
            DefaultTableModel dtm = (DefaultTableModel) GameTable.getModel();
            for(x = 0; x < dtm.getRowCount(); x++){
                for(y = 0; y < dtm.getColumnCount(); y++){
                    value = dtm.getValueAt(x, y).toString();
                    if(value.toLowerCase().contains(Searchbox.getText().toLowerCase()) == true){
                        keep = 1;
                    }
                }
                if (keep == 1){
                    keep = 0;
                }
                else{
                    dtm.removeRow(x);
                    x = x-1;
                }
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void AdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdSearchActionPerformed
        int x,keep = 0;
        DefaultTableModel dtm = (DefaultTableModel) GameTable.getModel();
        for(x = 0; x < dtm.getRowCount(); x++){
            if (Title.getText().equals("") != true && dtm.getValueAt(x, 0).toString().toLowerCase().contains(Title.getText().toLowerCase()) == true){
                keep = 1;
            }
            if (ESRB.getText().equals("") != true && dtm.getValueAt(x, 1).toString().toLowerCase().contains(ESRB.getText().toLowerCase()) == true){
                keep = 1;
            }
            if (Genre.getText().equals("") != true && dtm.getValueAt(x, 2).toString().toLowerCase().contains(Genre.getText().toLowerCase()) == true){
                keep = 1;
            }
            if (Rating.getText().equals("") != true && Rating.getText().equals(dtm.getValueAt(x, 3).toString()) == true){
                keep = 1;
            }
            if (keep == 1){
                keep = 0;
            }
            else{
                dtm.removeRow(x);
                x = x-1;
            }
        }
        Title.setText("");
        ESRB.setText("");
        Genre.setText("");
        Rating.setText("");
        AdvancedSearch.setVisible(false);
    }//GEN-LAST:event_AdSearchActionPerformed

    private void CancelASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelASActionPerformed
        Title.setText("");
        ESRB.setText("");
        Genre.setText("");
        Rating.setText("");
        Title.setText("");
        AdvancedSearch.setVisible(false); // makes screen invisisble
    }//GEN-LAST:event_CancelASActionPerformed

    private void AdvancedSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancedSearchButtonActionPerformed
        ResetButtonActionPerformed(evt);
        AdvancedSearch.setVisible(true);
    }//GEN-LAST:event_AdvancedSearchButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) GameTable.getModel();
        for(int i = dtm.getRowCount()-1;i >= 0;i--){
            dtm.removeRow(i);
        }
        try {
            games.makeGames(Tabletype);
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(ProjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        glist = games.getGames();
        for(Info game:glist){
            Object[] entry = {game.getTitle(),game.getESRB(),game.getGenre(),game.getRating()};
            dtm.addRow(entry);
        }
        InfoButton.setEnabled(false);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Info.dispose();
        Summarypane.setText(""); 
        Picturepane.setText("");
        if (Tabletype == 11){
            AllSystemTable.setVisible(true);
        }
        else{
            Table.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AdvancedSearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancedSearchButton1ActionPerformed
        ResetButton1ActionPerformed(evt);
        AdvancedSearch1.setVisible(true);
    }//GEN-LAST:event_AdvancedSearchButton1ActionPerformed

    private void ResetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) GameTable1.getModel();
        for(int i = 0;i < dtm.getRowCount();i++){
            dtm.removeRow(i);
        }
        try {
            games.makeGames(Tabletype);
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(ProjectFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        glist = games.getGames();
        for(Info game:glist){
            Object[] entry = {game.getTitle(),game.getESRB(),game.getGenre(),game.getSystem(),game.getRating()};
            dtm.addRow(entry);
        }
        InfoButton1.setEnabled(false);
    }//GEN-LAST:event_ResetButton1ActionPerformed

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
       ResetButtonActionPerformed(evt);
        if(Searchbox1.getText().equals("") != true){
            int x,y,keep = 0;
            String value;
            DefaultTableModel dtm = (DefaultTableModel) GameTable1.getModel();
            for(x = 0; x < dtm.getRowCount(); x++){
                for(y = 0; y < dtm.getColumnCount(); y++){
                    value = dtm.getValueAt(x, y).toString();
                    if(value.toLowerCase().contains(Searchbox1.getText().toLowerCase()) == true){
                        keep = 1;
                        Searchbox1.setText("");
                    }
                }
                if (keep == 1){
                    keep = 0;
                    Searchbox1.setText("");
                }
                else{
                    dtm.removeRow(x);
                    x = x-1;
                    Searchbox1.setText("");
                }
            }
        }
    }//GEN-LAST:event_SearchButton1ActionPerformed

    private void Searchbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Searchbox1ActionPerformed

    private void MainPageMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPageMenuItem1ActionPerformed
        AllSystemTable.dispose();
        InfoButton1.setEnabled(false);
        setVisible(true);
    }//GEN-LAST:event_MainPageMenuItem1ActionPerformed

    private void AllSystemTableWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AllSystemTableWindowClosing
        InfoButton1.setEnabled(false);
        setVisible(true);
    }//GEN-LAST:event_AllSystemTableWindowClosing

    private void AllSystemTableWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AllSystemTableWindowClosed
        InfoButton1.setEnabled(false);
        setVisible(true);
    }//GEN-LAST:event_AllSystemTableWindowClosed

    private void InfoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButton1ActionPerformed
        AllSystemTable.setVisible(false);
        Info.setVisible(true);
        DefaultTableModel dtm = (DefaultTableModel) GameTable1.getModel();
        for(Info g:glist){
            if(dtm.getValueAt(GameTable1.getSelectedRow(),0).equals(g.getTitle())&&dtm.getValueAt(GameTable1.getSelectedRow(),3).equals(g.getSystem())){
                
                Summarypane.setText(null);
                Summarypane.append("Title: " + g.getTitle()+"\n");
                Summarypane.append("ESRB: " + g.getESRB()+"\n");
                Summarypane.append("Genre: " + g.getGenre()+"\n");
                Summarypane.append("Rating: " + g.getRating()+"\n");
                Summarypane.append("System: " + g.getSystem()+"\n");
                Summarypane.append("\n");
                Summarypane.append("Summary: " + g.getSummary()+"\n");
                Summarypane.setEditable(false);
                Picturepane.insertIcon(new ImageIcon(g.getPic()));
                Picturepane.setEditable(false);
            }
        }
    }//GEN-LAST:event_InfoButton1ActionPerformed

    private void InfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButtonActionPerformed
        Table.setVisible(false);
        Info.setVisible(true);
        DefaultTableModel dtm = (DefaultTableModel) GameTable.getModel();
        for(Info g:glist){
            if(dtm.getValueAt(GameTable.getSelectedRow(),0).equals(g.getTitle())){
                
                Summarypane.setText(null);
                Summarypane.append("Title: " + g.getTitle()+"\n");
                Summarypane.append("ESRB: " + g.getESRB()+"\n");
                Summarypane.append("Genre: " + g.getGenre()+"\n");
                Summarypane.append("Rating: " + g.getRating()+"\n");
                Summarypane.append("\n");
                Summarypane.append("Summary: " + g.getSummary()+"\n");
                Picturepane.insertIcon(new ImageIcon(g.getPic()));
                Summarypane.setEditable(false);
                Picturepane.setEditable(false);
            }
        }
    }//GEN-LAST:event_InfoButtonActionPerformed

    private void AdSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdSearch1ActionPerformed
        int x,y,keep = 0;
        DefaultTableModel dtm = (DefaultTableModel) GameTable1.getModel();
        for(x = 0; x < dtm.getRowCount(); x++){
            if (Title1.getText().equals("") != true && dtm.getValueAt(x, 0).toString().toLowerCase().contains(Title1.getText().toLowerCase()) == true){
                keep = 1;
            }
            if (ESRB1.getText().equals("") != true && dtm.getValueAt(x, 1).toString().toLowerCase().contains(ESRB1.getText().toLowerCase()) == true){
                keep = 1;
            }
            if (Genre1.getText().equals("") != true && dtm.getValueAt(x, 2).toString().toLowerCase().contains(Genre1.getText().toLowerCase()) == true){
                keep = 1;
            }
            if (Rating1.getText().equals("") != true && Rating1.getText().equals(dtm.getValueAt(x, 3).toString()) == true){
                keep = 1;
            }
            if (Sys1.getText().equals("") != true && Sys1.getText().toLowerCase().equals(dtm.getValueAt(x, 3).toString().toLowerCase()) == true){
                keep = 1;
            }
            if (keep == 1){
                keep = 0;
            }
            else{
                dtm.removeRow(x);
                x = x-1;
            }
        }
        Title1.setText("");
        ESRB1.setText("");
        Genre1.setText("");
        Rating1.setText("");
        Sys1.setText("");
        AdvancedSearch1.setVisible(false);
    }//GEN-LAST:event_AdSearch1ActionPerformed

    private void CancelAS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAS1ActionPerformed
        Title1.setText("");
        ESRB1.setText("");
        Genre1.setText("");
        Rating1.setText("");
        Sys1.setText("");
        AdvancedSearch1.setVisible(false); // makes screen invisisble
    }//GEN-LAST:event_CancelAS1ActionPerformed

    private void GameTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GameTableMouseClicked
        InfoButton.setEnabled(true);
    }//GEN-LAST:event_GameTableMouseClicked

    private void GameTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GameTable1MouseClicked
        InfoButton1.setEnabled(true);
    }//GEN-LAST:event_GameTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GameModel games = new GameModel();
                new ProjectFrame(games).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdSearch;
    private javax.swing.JButton AdSearch1;
    private javax.swing.JDialog AdvancedSearch;
    private javax.swing.JDialog AdvancedSearch1;
    private javax.swing.JButton AdvancedSearchButton;
    private javax.swing.JButton AdvancedSearchButton1;
    private javax.swing.JButton AllButton;
    private javax.swing.JDialog AllSystemTable;
    private javax.swing.JButton CancelAS;
    private javax.swing.JButton CancelAS1;
    private javax.swing.JTextField ESRB;
    private javax.swing.JTextField ESRB1;
    private javax.swing.JMenu Exit;
    private javax.swing.JButton GBAButton;
    private javax.swing.JMenuItem GBAMenuItem;
    private javax.swing.JButton GBCButton;
    private javax.swing.JMenuItem GBCMenuItem;
    private javax.swing.JTable GameTable;
    private javax.swing.JTable GameTable1;
    private javax.swing.JButton GamecubeButton;
    private javax.swing.JMenuItem GamecubeMenuItem;
    private javax.swing.JTextField Genre;
    private javax.swing.JTextField Genre1;
    private javax.swing.JDialog Info;
    private javax.swing.JButton InfoButton;
    private javax.swing.JButton InfoButton1;
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton LinuxButton;
    private javax.swing.JMenuItem LinuxMenuItem;
    private javax.swing.JButton MacButton;
    private javax.swing.JMenuItem MacMenuItem;
    private javax.swing.JMenuItem MainPageMenuItem;
    private javax.swing.JMenuItem MainPageMenuItem1;
    private javax.swing.JMenuItem N64MenuItem;
    private javax.swing.JButton Nintendo3DSButton;
    private javax.swing.JMenuItem Nintendo3DSMenuItem;
    private javax.swing.JButton Nintendo64Button;
    private javax.swing.JButton NintendoDSButton;
    private javax.swing.JMenuItem NintendoDSMenuItem;
    private javax.swing.JButton PCButton;
    private javax.swing.JMenuItem PCMenuItem;
    private javax.swing.JButton PS2Button;
    private javax.swing.JMenuItem PS2MenuItem;
    private javax.swing.JButton PS3Button;
    private javax.swing.JMenuItem PS3MenuItem;
    private javax.swing.JButton PS4Button;
    private javax.swing.JMenuItem PS4MenuItem;
    private javax.swing.JButton PSPButton;
    private javax.swing.JMenuItem PSPMenuItem;
    private javax.swing.JButton PSVButton;
    private javax.swing.JMenuItem PSVMenuItem;
    private javax.swing.JTextPane Picturepane;
    private javax.swing.JTextField Rating;
    private javax.swing.JTextField Rating1;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton ResetButton1;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SearchButton1;
    private javax.swing.JTextField Searchbox;
    private javax.swing.JTextField Searchbox1;
    private javax.swing.JTextArea Summarypane;
    private javax.swing.JTextField Sys1;
    private javax.swing.JDialog Table;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField Title1;
    private javax.swing.JButton WiiButton;
    private javax.swing.JMenuItem WiiMenuItem;
    private javax.swing.JButton WiiUButton;
    private javax.swing.JMenuItem WiiUMenuItem;
    private javax.swing.JButton Xbox360Button;
    private javax.swing.JMenuItem Xbox360MenuItem;
    private javax.swing.JButton XboxButton;
    private javax.swing.JMenuItem XboxMenuItem;
    private javax.swing.JButton XboxOneButton;
    private javax.swing.JMenuItem XboxOneMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
